language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: biDZhkeKyt7wzNBSPampPJEKEAE5ZclwIyqEVczrRJRQzBAdgpnCkRWvvz0Oi+1P6RdM0yMsebNvloXiALiGMt1LsH0Cz+ItGzNq2S/EMj/mmhTU3jPgYETOx4K0d8AxyQqBX7OQqCV9sXX4pRsfEfuqip/qlyl/nMalPQEcebbECQlO3C0S+d1asYqSujeu//6vIE0t6zd58e63EjuyjtAgmSCOLZ6PGwJBB1K1Z0FK6CFICEV9bMXcbUSVxGB7j4daR4cyJRIhpGZWGMFIjFO0BUsFRoOpCzyf0uxsXNRk8fkO+ClT4WnlnOnHTvqOg8gfQeD6/l7Vlr2qFryUGcmlcsWV7rlkfSeAo9+gGPRHpNp6upSZz+RSekBJ8MZYzMMUFy22FrLDRUqBAmSuWoScHbh8MJT7rTXzz0yHJbr0w8I17xBt9LH6ye+rLP04M1s4BlqIh2zv07dKDRzvwd04mAPqstlStUiPR5CUKzJGRjqCHhH/22EMEpJrQkI4A+zXis2TzD3XORimuIQNpZmwbnoTXVhMUwOouU+IbT1HStLoTC3dQCehxuLYNxHJBNEjhtjqi9heGLGpBBMzl98B83pDrJhU8o53K97hfIm84p9iJt9oz5Oom1hMdLhquCwFy4hsJTxQVwn6TPN4YFa0wPXTdASof6szptPxSws=
  app:
    master: miteb-backend-dev
    prod: miteb-backend-prod